//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatClient.MyServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisplayNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AvatarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ChatClient.MyServiceReference.Chat[] ChatsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ChatClient.MyServiceReference.Chat[] Chats1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DisplayName {
            get {
                return this.DisplayNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayNameField, value) != true)) {
                    this.DisplayNameField = value;
                    this.RaisePropertyChanged("DisplayName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Avatar {
            get {
                return this.AvatarField;
            }
            set {
                if ((object.ReferenceEquals(this.AvatarField, value) != true)) {
                    this.AvatarField = value;
                    this.RaisePropertyChanged("Avatar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public ChatClient.MyServiceReference.Chat[] Chats {
            get {
                return this.ChatsField;
            }
            set {
                if ((object.ReferenceEquals(this.ChatsField, value) != true)) {
                    this.ChatsField = value;
                    this.RaisePropertyChanged("Chats");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public ChatClient.MyServiceReference.Chat[] Chats1 {
            get {
                return this.Chats1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Chats1Field, value) != true)) {
                    this.Chats1Field = value;
                    this.RaisePropertyChanged("Chats1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Chat", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Chat : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        private System.Nullable<System.DateTime> SendTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiverField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ChatClient.MyServiceReference.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ChatClient.MyServiceReference.User User1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> SendTime {
            get {
                return this.SendTimeField;
            }
            set {
                if ((this.SendTimeField.Equals(value) != true)) {
                    this.SendTimeField = value;
                    this.RaisePropertyChanged("SendTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Sender {
            get {
                return this.SenderField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderField, value) != true)) {
                    this.SenderField = value;
                    this.RaisePropertyChanged("Sender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Receiver {
            get {
                return this.ReceiverField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiverField, value) != true)) {
                    this.ReceiverField = value;
                    this.RaisePropertyChanged("Receiver");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public ChatClient.MyServiceReference.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public ChatClient.MyServiceReference.User User1 {
            get {
                return this.User1Field;
            }
            set {
                if ((object.ReferenceEquals(this.User1Field, value) != true)) {
                    this.User1Field = value;
                    this.RaisePropertyChanged("User1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyServiceReference.MyWebServiceSoap")]
    public interface MyWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SignIn", ReplyAction="*")]
        ChatClient.MyServiceReference.SignInResponse SignIn(ChatClient.MyServiceReference.SignInRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SignIn", ReplyAction="*")]
        System.Threading.Tasks.Task<ChatClient.MyServiceReference.SignInResponse> SignInAsync(ChatClient.MyServiceReference.SignInRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SignUp", ReplyAction="*")]
        ChatClient.MyServiceReference.SignUpResponse SignUp(ChatClient.MyServiceReference.SignUpRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SignUp", ReplyAction="*")]
        System.Threading.Tasks.Task<ChatClient.MyServiceReference.SignUpResponse> SignUpAsync(ChatClient.MyServiceReference.SignUpRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateInformation", ReplyAction="*")]
        ChatClient.MyServiceReference.UpdateInformationResponse UpdateInformation(ChatClient.MyServiceReference.UpdateInformationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateInformation", ReplyAction="*")]
        System.Threading.Tasks.Task<ChatClient.MyServiceReference.UpdateInformationResponse> UpdateInformationAsync(ChatClient.MyServiceReference.UpdateInformationRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUser", ReplyAction="*")]
        ChatClient.MyServiceReference.GetUserResponse GetUser(ChatClient.MyServiceReference.GetUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUser", ReplyAction="*")]
        System.Threading.Tasks.Task<ChatClient.MyServiceReference.GetUserResponse> GetUserAsync(ChatClient.MyServiceReference.GetUserRequest request);
        
        // CODEGEN: Generating message contract since element name filePath from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetImage", ReplyAction="*")]
        ChatClient.MyServiceReference.GetImageResponse GetImage(ChatClient.MyServiceReference.GetImageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetImage", ReplyAction="*")]
        System.Threading.Tasks.Task<ChatClient.MyServiceReference.GetImageResponse> GetImageAsync(ChatClient.MyServiceReference.GetImageRequest request);
        
        // CODEGEN: Generating message contract since element name exceptUsername from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetListUser", ReplyAction="*")]
        ChatClient.MyServiceReference.GetListUserResponse GetListUser(ChatClient.MyServiceReference.GetListUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetListUser", ReplyAction="*")]
        System.Threading.Tasks.Task<ChatClient.MyServiceReference.GetListUserResponse> GetListUserAsync(ChatClient.MyServiceReference.GetListUserRequest request);
        
        // CODEGEN: Generating message contract since element name sender from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessages", ReplyAction="*")]
        ChatClient.MyServiceReference.GetMessagesResponse GetMessages(ChatClient.MyServiceReference.GetMessagesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessages", ReplyAction="*")]
        System.Threading.Tasks.Task<ChatClient.MyServiceReference.GetMessagesResponse> GetMessagesAsync(ChatClient.MyServiceReference.GetMessagesRequest request);
        
        // CODEGEN: Generating message contract since element name sender from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddMessage", ReplyAction="*")]
        ChatClient.MyServiceReference.AddMessageResponse AddMessage(ChatClient.MyServiceReference.AddMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<ChatClient.MyServiceReference.AddMessageResponse> AddMessageAsync(ChatClient.MyServiceReference.AddMessageRequest request);
        
        // CODEGEN: Generating message contract since element name DeleteMessageResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteMessage", ReplyAction="*")]
        ChatClient.MyServiceReference.DeleteMessageResponse DeleteMessage(ChatClient.MyServiceReference.DeleteMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<ChatClient.MyServiceReference.DeleteMessageResponse> DeleteMessageAsync(ChatClient.MyServiceReference.DeleteMessageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignInRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SignIn", Namespace="http://tempuri.org/", Order=0)]
        public ChatClient.MyServiceReference.SignInRequestBody Body;
        
        public SignInRequest() {
        }
        
        public SignInRequest(ChatClient.MyServiceReference.SignInRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SignInRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public SignInRequestBody() {
        }
        
        public SignInRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignInResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SignInResponse", Namespace="http://tempuri.org/", Order=0)]
        public ChatClient.MyServiceReference.SignInResponseBody Body;
        
        public SignInResponse() {
        }
        
        public SignInResponse(ChatClient.MyServiceReference.SignInResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SignInResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ChatClient.MyServiceReference.User SignInResult;
        
        public SignInResponseBody() {
        }
        
        public SignInResponseBody(ChatClient.MyServiceReference.User SignInResult) {
            this.SignInResult = SignInResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignUpRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SignUp", Namespace="http://tempuri.org/", Order=0)]
        public ChatClient.MyServiceReference.SignUpRequestBody Body;
        
        public SignUpRequest() {
        }
        
        public SignUpRequest(ChatClient.MyServiceReference.SignUpRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SignUpRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string displayName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string filePath;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public byte[] file_byte;
        
        public SignUpRequestBody() {
        }
        
        public SignUpRequestBody(string username, string password, string displayName, string filePath, byte[] file_byte) {
            this.username = username;
            this.password = password;
            this.displayName = displayName;
            this.filePath = filePath;
            this.file_byte = file_byte;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignUpResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SignUpResponse", Namespace="http://tempuri.org/", Order=0)]
        public ChatClient.MyServiceReference.SignUpResponseBody Body;
        
        public SignUpResponse() {
        }
        
        public SignUpResponse(ChatClient.MyServiceReference.SignUpResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SignUpResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SignUpResult;
        
        public SignUpResponseBody() {
        }
        
        public SignUpResponseBody(string SignUpResult) {
            this.SignUpResult = SignUpResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateInformationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateInformation", Namespace="http://tempuri.org/", Order=0)]
        public ChatClient.MyServiceReference.UpdateInformationRequestBody Body;
        
        public UpdateInformationRequest() {
        }
        
        public UpdateInformationRequest(ChatClient.MyServiceReference.UpdateInformationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateInformationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string displayName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string oldPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string newPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string filePath;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public byte[] file_byte;
        
        public UpdateInformationRequestBody() {
        }
        
        public UpdateInformationRequestBody(string username, string displayName, string oldPassword, string newPassword, string filePath, byte[] file_byte) {
            this.username = username;
            this.displayName = displayName;
            this.oldPassword = oldPassword;
            this.newPassword = newPassword;
            this.filePath = filePath;
            this.file_byte = file_byte;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateInformationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateInformationResponse", Namespace="http://tempuri.org/", Order=0)]
        public ChatClient.MyServiceReference.UpdateInformationResponseBody Body;
        
        public UpdateInformationResponse() {
        }
        
        public UpdateInformationResponse(ChatClient.MyServiceReference.UpdateInformationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateInformationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateInformationResult;
        
        public UpdateInformationResponseBody() {
        }
        
        public UpdateInformationResponseBody(string UpdateInformationResult) {
            this.UpdateInformationResult = UpdateInformationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUser", Namespace="http://tempuri.org/", Order=0)]
        public ChatClient.MyServiceReference.GetUserRequestBody Body;
        
        public GetUserRequest() {
        }
        
        public GetUserRequest(ChatClient.MyServiceReference.GetUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        public GetUserRequestBody() {
        }
        
        public GetUserRequestBody(string username) {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public ChatClient.MyServiceReference.GetUserResponseBody Body;
        
        public GetUserResponse() {
        }
        
        public GetUserResponse(ChatClient.MyServiceReference.GetUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ChatClient.MyServiceReference.User GetUserResult;
        
        public GetUserResponseBody() {
        }
        
        public GetUserResponseBody(ChatClient.MyServiceReference.User GetUserResult) {
            this.GetUserResult = GetUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetImageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetImage", Namespace="http://tempuri.org/", Order=0)]
        public ChatClient.MyServiceReference.GetImageRequestBody Body;
        
        public GetImageRequest() {
        }
        
        public GetImageRequest(ChatClient.MyServiceReference.GetImageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetImageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string filePath;
        
        public GetImageRequestBody() {
        }
        
        public GetImageRequestBody(string filePath) {
            this.filePath = filePath;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetImageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetImageResponse", Namespace="http://tempuri.org/", Order=0)]
        public ChatClient.MyServiceReference.GetImageResponseBody Body;
        
        public GetImageResponse() {
        }
        
        public GetImageResponse(ChatClient.MyServiceReference.GetImageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetImageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] GetImageResult;
        
        public GetImageResponseBody() {
        }
        
        public GetImageResponseBody(byte[] GetImageResult) {
            this.GetImageResult = GetImageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListUser", Namespace="http://tempuri.org/", Order=0)]
        public ChatClient.MyServiceReference.GetListUserRequestBody Body;
        
        public GetListUserRequest() {
        }
        
        public GetListUserRequest(ChatClient.MyServiceReference.GetListUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetListUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string exceptUsername;
        
        public GetListUserRequestBody() {
        }
        
        public GetListUserRequestBody(string exceptUsername) {
            this.exceptUsername = exceptUsername;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public ChatClient.MyServiceReference.GetListUserResponseBody Body;
        
        public GetListUserResponse() {
        }
        
        public GetListUserResponse(ChatClient.MyServiceReference.GetListUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetListUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ChatClient.MyServiceReference.User[] GetListUserResult;
        
        public GetListUserResponseBody() {
        }
        
        public GetListUserResponseBody(ChatClient.MyServiceReference.User[] GetListUserResult) {
            this.GetListUserResult = GetListUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessagesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessages", Namespace="http://tempuri.org/", Order=0)]
        public ChatClient.MyServiceReference.GetMessagesRequestBody Body;
        
        public GetMessagesRequest() {
        }
        
        public GetMessagesRequest(ChatClient.MyServiceReference.GetMessagesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMessagesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sender;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string receiver;
        
        public GetMessagesRequestBody() {
        }
        
        public GetMessagesRequestBody(string sender, string receiver) {
            this.sender = sender;
            this.receiver = receiver;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessagesResponse", Namespace="http://tempuri.org/", Order=0)]
        public ChatClient.MyServiceReference.GetMessagesResponseBody Body;
        
        public GetMessagesResponse() {
        }
        
        public GetMessagesResponse(ChatClient.MyServiceReference.GetMessagesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMessagesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ChatClient.MyServiceReference.Chat[] GetMessagesResult;
        
        public GetMessagesResponseBody() {
        }
        
        public GetMessagesResponseBody(ChatClient.MyServiceReference.Chat[] GetMessagesResult) {
            this.GetMessagesResult = GetMessagesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddMessage", Namespace="http://tempuri.org/", Order=0)]
        public ChatClient.MyServiceReference.AddMessageRequestBody Body;
        
        public AddMessageRequest() {
        }
        
        public AddMessageRequest(ChatClient.MyServiceReference.AddMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sender;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string receiver;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string message;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime sendTime;
        
        public AddMessageRequestBody() {
        }
        
        public AddMessageRequestBody(string sender, string receiver, string message, System.DateTime sendTime) {
            this.sender = sender;
            this.receiver = receiver;
            this.message = message;
            this.sendTime = sendTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddMessageResponse", Namespace="http://tempuri.org/", Order=0)]
        public ChatClient.MyServiceReference.AddMessageResponseBody Body;
        
        public AddMessageResponse() {
        }
        
        public AddMessageResponse(ChatClient.MyServiceReference.AddMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddMessageResult;
        
        public AddMessageResponseBody() {
        }
        
        public AddMessageResponseBody(string AddMessageResult) {
            this.AddMessageResult = AddMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteMessage", Namespace="http://tempuri.org/", Order=0)]
        public ChatClient.MyServiceReference.DeleteMessageRequestBody Body;
        
        public DeleteMessageRequest() {
        }
        
        public DeleteMessageRequest(ChatClient.MyServiceReference.DeleteMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public DeleteMessageRequestBody() {
        }
        
        public DeleteMessageRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteMessageResponse", Namespace="http://tempuri.org/", Order=0)]
        public ChatClient.MyServiceReference.DeleteMessageResponseBody Body;
        
        public DeleteMessageResponse() {
        }
        
        public DeleteMessageResponse(ChatClient.MyServiceReference.DeleteMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteMessageResult;
        
        public DeleteMessageResponseBody() {
        }
        
        public DeleteMessageResponseBody(string DeleteMessageResult) {
            this.DeleteMessageResult = DeleteMessageResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MyWebServiceSoapChannel : ChatClient.MyServiceReference.MyWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyWebServiceSoapClient : System.ServiceModel.ClientBase<ChatClient.MyServiceReference.MyWebServiceSoap>, ChatClient.MyServiceReference.MyWebServiceSoap {
        
        public MyWebServiceSoapClient() {
        }
        
        public MyWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChatClient.MyServiceReference.SignInResponse ChatClient.MyServiceReference.MyWebServiceSoap.SignIn(ChatClient.MyServiceReference.SignInRequest request) {
            return base.Channel.SignIn(request);
        }
        
        public ChatClient.MyServiceReference.User SignIn(string username, string password) {
            ChatClient.MyServiceReference.SignInRequest inValue = new ChatClient.MyServiceReference.SignInRequest();
            inValue.Body = new ChatClient.MyServiceReference.SignInRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            ChatClient.MyServiceReference.SignInResponse retVal = ((ChatClient.MyServiceReference.MyWebServiceSoap)(this)).SignIn(inValue);
            return retVal.Body.SignInResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ChatClient.MyServiceReference.SignInResponse> ChatClient.MyServiceReference.MyWebServiceSoap.SignInAsync(ChatClient.MyServiceReference.SignInRequest request) {
            return base.Channel.SignInAsync(request);
        }
        
        public System.Threading.Tasks.Task<ChatClient.MyServiceReference.SignInResponse> SignInAsync(string username, string password) {
            ChatClient.MyServiceReference.SignInRequest inValue = new ChatClient.MyServiceReference.SignInRequest();
            inValue.Body = new ChatClient.MyServiceReference.SignInRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((ChatClient.MyServiceReference.MyWebServiceSoap)(this)).SignInAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChatClient.MyServiceReference.SignUpResponse ChatClient.MyServiceReference.MyWebServiceSoap.SignUp(ChatClient.MyServiceReference.SignUpRequest request) {
            return base.Channel.SignUp(request);
        }
        
        public string SignUp(string username, string password, string displayName, string filePath, byte[] file_byte) {
            ChatClient.MyServiceReference.SignUpRequest inValue = new ChatClient.MyServiceReference.SignUpRequest();
            inValue.Body = new ChatClient.MyServiceReference.SignUpRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.displayName = displayName;
            inValue.Body.filePath = filePath;
            inValue.Body.file_byte = file_byte;
            ChatClient.MyServiceReference.SignUpResponse retVal = ((ChatClient.MyServiceReference.MyWebServiceSoap)(this)).SignUp(inValue);
            return retVal.Body.SignUpResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ChatClient.MyServiceReference.SignUpResponse> ChatClient.MyServiceReference.MyWebServiceSoap.SignUpAsync(ChatClient.MyServiceReference.SignUpRequest request) {
            return base.Channel.SignUpAsync(request);
        }
        
        public System.Threading.Tasks.Task<ChatClient.MyServiceReference.SignUpResponse> SignUpAsync(string username, string password, string displayName, string filePath, byte[] file_byte) {
            ChatClient.MyServiceReference.SignUpRequest inValue = new ChatClient.MyServiceReference.SignUpRequest();
            inValue.Body = new ChatClient.MyServiceReference.SignUpRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.displayName = displayName;
            inValue.Body.filePath = filePath;
            inValue.Body.file_byte = file_byte;
            return ((ChatClient.MyServiceReference.MyWebServiceSoap)(this)).SignUpAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChatClient.MyServiceReference.UpdateInformationResponse ChatClient.MyServiceReference.MyWebServiceSoap.UpdateInformation(ChatClient.MyServiceReference.UpdateInformationRequest request) {
            return base.Channel.UpdateInformation(request);
        }
        
        public string UpdateInformation(string username, string displayName, string oldPassword, string newPassword, string filePath, byte[] file_byte) {
            ChatClient.MyServiceReference.UpdateInformationRequest inValue = new ChatClient.MyServiceReference.UpdateInformationRequest();
            inValue.Body = new ChatClient.MyServiceReference.UpdateInformationRequestBody();
            inValue.Body.username = username;
            inValue.Body.displayName = displayName;
            inValue.Body.oldPassword = oldPassword;
            inValue.Body.newPassword = newPassword;
            inValue.Body.filePath = filePath;
            inValue.Body.file_byte = file_byte;
            ChatClient.MyServiceReference.UpdateInformationResponse retVal = ((ChatClient.MyServiceReference.MyWebServiceSoap)(this)).UpdateInformation(inValue);
            return retVal.Body.UpdateInformationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ChatClient.MyServiceReference.UpdateInformationResponse> ChatClient.MyServiceReference.MyWebServiceSoap.UpdateInformationAsync(ChatClient.MyServiceReference.UpdateInformationRequest request) {
            return base.Channel.UpdateInformationAsync(request);
        }
        
        public System.Threading.Tasks.Task<ChatClient.MyServiceReference.UpdateInformationResponse> UpdateInformationAsync(string username, string displayName, string oldPassword, string newPassword, string filePath, byte[] file_byte) {
            ChatClient.MyServiceReference.UpdateInformationRequest inValue = new ChatClient.MyServiceReference.UpdateInformationRequest();
            inValue.Body = new ChatClient.MyServiceReference.UpdateInformationRequestBody();
            inValue.Body.username = username;
            inValue.Body.displayName = displayName;
            inValue.Body.oldPassword = oldPassword;
            inValue.Body.newPassword = newPassword;
            inValue.Body.filePath = filePath;
            inValue.Body.file_byte = file_byte;
            return ((ChatClient.MyServiceReference.MyWebServiceSoap)(this)).UpdateInformationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChatClient.MyServiceReference.GetUserResponse ChatClient.MyServiceReference.MyWebServiceSoap.GetUser(ChatClient.MyServiceReference.GetUserRequest request) {
            return base.Channel.GetUser(request);
        }
        
        public ChatClient.MyServiceReference.User GetUser(string username) {
            ChatClient.MyServiceReference.GetUserRequest inValue = new ChatClient.MyServiceReference.GetUserRequest();
            inValue.Body = new ChatClient.MyServiceReference.GetUserRequestBody();
            inValue.Body.username = username;
            ChatClient.MyServiceReference.GetUserResponse retVal = ((ChatClient.MyServiceReference.MyWebServiceSoap)(this)).GetUser(inValue);
            return retVal.Body.GetUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ChatClient.MyServiceReference.GetUserResponse> ChatClient.MyServiceReference.MyWebServiceSoap.GetUserAsync(ChatClient.MyServiceReference.GetUserRequest request) {
            return base.Channel.GetUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<ChatClient.MyServiceReference.GetUserResponse> GetUserAsync(string username) {
            ChatClient.MyServiceReference.GetUserRequest inValue = new ChatClient.MyServiceReference.GetUserRequest();
            inValue.Body = new ChatClient.MyServiceReference.GetUserRequestBody();
            inValue.Body.username = username;
            return ((ChatClient.MyServiceReference.MyWebServiceSoap)(this)).GetUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChatClient.MyServiceReference.GetImageResponse ChatClient.MyServiceReference.MyWebServiceSoap.GetImage(ChatClient.MyServiceReference.GetImageRequest request) {
            return base.Channel.GetImage(request);
        }
        
        public byte[] GetImage(string filePath) {
            ChatClient.MyServiceReference.GetImageRequest inValue = new ChatClient.MyServiceReference.GetImageRequest();
            inValue.Body = new ChatClient.MyServiceReference.GetImageRequestBody();
            inValue.Body.filePath = filePath;
            ChatClient.MyServiceReference.GetImageResponse retVal = ((ChatClient.MyServiceReference.MyWebServiceSoap)(this)).GetImage(inValue);
            return retVal.Body.GetImageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ChatClient.MyServiceReference.GetImageResponse> ChatClient.MyServiceReference.MyWebServiceSoap.GetImageAsync(ChatClient.MyServiceReference.GetImageRequest request) {
            return base.Channel.GetImageAsync(request);
        }
        
        public System.Threading.Tasks.Task<ChatClient.MyServiceReference.GetImageResponse> GetImageAsync(string filePath) {
            ChatClient.MyServiceReference.GetImageRequest inValue = new ChatClient.MyServiceReference.GetImageRequest();
            inValue.Body = new ChatClient.MyServiceReference.GetImageRequestBody();
            inValue.Body.filePath = filePath;
            return ((ChatClient.MyServiceReference.MyWebServiceSoap)(this)).GetImageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChatClient.MyServiceReference.GetListUserResponse ChatClient.MyServiceReference.MyWebServiceSoap.GetListUser(ChatClient.MyServiceReference.GetListUserRequest request) {
            return base.Channel.GetListUser(request);
        }
        
        public ChatClient.MyServiceReference.User[] GetListUser(string exceptUsername) {
            ChatClient.MyServiceReference.GetListUserRequest inValue = new ChatClient.MyServiceReference.GetListUserRequest();
            inValue.Body = new ChatClient.MyServiceReference.GetListUserRequestBody();
            inValue.Body.exceptUsername = exceptUsername;
            ChatClient.MyServiceReference.GetListUserResponse retVal = ((ChatClient.MyServiceReference.MyWebServiceSoap)(this)).GetListUser(inValue);
            return retVal.Body.GetListUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ChatClient.MyServiceReference.GetListUserResponse> ChatClient.MyServiceReference.MyWebServiceSoap.GetListUserAsync(ChatClient.MyServiceReference.GetListUserRequest request) {
            return base.Channel.GetListUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<ChatClient.MyServiceReference.GetListUserResponse> GetListUserAsync(string exceptUsername) {
            ChatClient.MyServiceReference.GetListUserRequest inValue = new ChatClient.MyServiceReference.GetListUserRequest();
            inValue.Body = new ChatClient.MyServiceReference.GetListUserRequestBody();
            inValue.Body.exceptUsername = exceptUsername;
            return ((ChatClient.MyServiceReference.MyWebServiceSoap)(this)).GetListUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChatClient.MyServiceReference.GetMessagesResponse ChatClient.MyServiceReference.MyWebServiceSoap.GetMessages(ChatClient.MyServiceReference.GetMessagesRequest request) {
            return base.Channel.GetMessages(request);
        }
        
        public ChatClient.MyServiceReference.Chat[] GetMessages(string sender, string receiver) {
            ChatClient.MyServiceReference.GetMessagesRequest inValue = new ChatClient.MyServiceReference.GetMessagesRequest();
            inValue.Body = new ChatClient.MyServiceReference.GetMessagesRequestBody();
            inValue.Body.sender = sender;
            inValue.Body.receiver = receiver;
            ChatClient.MyServiceReference.GetMessagesResponse retVal = ((ChatClient.MyServiceReference.MyWebServiceSoap)(this)).GetMessages(inValue);
            return retVal.Body.GetMessagesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ChatClient.MyServiceReference.GetMessagesResponse> ChatClient.MyServiceReference.MyWebServiceSoap.GetMessagesAsync(ChatClient.MyServiceReference.GetMessagesRequest request) {
            return base.Channel.GetMessagesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ChatClient.MyServiceReference.GetMessagesResponse> GetMessagesAsync(string sender, string receiver) {
            ChatClient.MyServiceReference.GetMessagesRequest inValue = new ChatClient.MyServiceReference.GetMessagesRequest();
            inValue.Body = new ChatClient.MyServiceReference.GetMessagesRequestBody();
            inValue.Body.sender = sender;
            inValue.Body.receiver = receiver;
            return ((ChatClient.MyServiceReference.MyWebServiceSoap)(this)).GetMessagesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChatClient.MyServiceReference.AddMessageResponse ChatClient.MyServiceReference.MyWebServiceSoap.AddMessage(ChatClient.MyServiceReference.AddMessageRequest request) {
            return base.Channel.AddMessage(request);
        }
        
        public string AddMessage(string sender, string receiver, string message, System.DateTime sendTime) {
            ChatClient.MyServiceReference.AddMessageRequest inValue = new ChatClient.MyServiceReference.AddMessageRequest();
            inValue.Body = new ChatClient.MyServiceReference.AddMessageRequestBody();
            inValue.Body.sender = sender;
            inValue.Body.receiver = receiver;
            inValue.Body.message = message;
            inValue.Body.sendTime = sendTime;
            ChatClient.MyServiceReference.AddMessageResponse retVal = ((ChatClient.MyServiceReference.MyWebServiceSoap)(this)).AddMessage(inValue);
            return retVal.Body.AddMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ChatClient.MyServiceReference.AddMessageResponse> ChatClient.MyServiceReference.MyWebServiceSoap.AddMessageAsync(ChatClient.MyServiceReference.AddMessageRequest request) {
            return base.Channel.AddMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<ChatClient.MyServiceReference.AddMessageResponse> AddMessageAsync(string sender, string receiver, string message, System.DateTime sendTime) {
            ChatClient.MyServiceReference.AddMessageRequest inValue = new ChatClient.MyServiceReference.AddMessageRequest();
            inValue.Body = new ChatClient.MyServiceReference.AddMessageRequestBody();
            inValue.Body.sender = sender;
            inValue.Body.receiver = receiver;
            inValue.Body.message = message;
            inValue.Body.sendTime = sendTime;
            return ((ChatClient.MyServiceReference.MyWebServiceSoap)(this)).AddMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChatClient.MyServiceReference.DeleteMessageResponse ChatClient.MyServiceReference.MyWebServiceSoap.DeleteMessage(ChatClient.MyServiceReference.DeleteMessageRequest request) {
            return base.Channel.DeleteMessage(request);
        }
        
        public string DeleteMessage(int id) {
            ChatClient.MyServiceReference.DeleteMessageRequest inValue = new ChatClient.MyServiceReference.DeleteMessageRequest();
            inValue.Body = new ChatClient.MyServiceReference.DeleteMessageRequestBody();
            inValue.Body.id = id;
            ChatClient.MyServiceReference.DeleteMessageResponse retVal = ((ChatClient.MyServiceReference.MyWebServiceSoap)(this)).DeleteMessage(inValue);
            return retVal.Body.DeleteMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ChatClient.MyServiceReference.DeleteMessageResponse> ChatClient.MyServiceReference.MyWebServiceSoap.DeleteMessageAsync(ChatClient.MyServiceReference.DeleteMessageRequest request) {
            return base.Channel.DeleteMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<ChatClient.MyServiceReference.DeleteMessageResponse> DeleteMessageAsync(int id) {
            ChatClient.MyServiceReference.DeleteMessageRequest inValue = new ChatClient.MyServiceReference.DeleteMessageRequest();
            inValue.Body = new ChatClient.MyServiceReference.DeleteMessageRequestBody();
            inValue.Body.id = id;
            return ((ChatClient.MyServiceReference.MyWebServiceSoap)(this)).DeleteMessageAsync(inValue);
        }
    }
}
